config/routes.rb
Rails.application.routes.draw do
	
  resource :eventracker, only: [:edit, :update]

  resolve("Eventracker") { [:eventacker] }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
include Redmine::Hook::Helper
include EventrackerHookListener
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

# TODO other controllers : issues, attachements
 def edit
 
 end


 def update
 	@news.comments.find(params[:comment_id]).update(comment_params)
 	render :action => 'update'
 	Redmine::Hook::listener::Eventracker.everntracker(comment_params)
 end

 private

def comment_params
	params(:comment).require(:commented_type, :commented_id, :author)
end
	
end

app/controllers/eventracker.controller.rb
class EventrackerController < ApplicationController 

 def edit 
	@config = Eventracker::Config.instance
 end

 def update 
  Eventracker::Config.instance.webhook_url = params[:eventracker_config][:webhook_url]
  redirect_to :home
 end

end

app/controllers/eventracker_controller.rb
class EventrackerController < ApplicationController 

 def edit 
	@config = Eventracker::Config.instance
 end

 def update 
  Eventracker::Config.instance.webhook_url = params[:eventracker_config][:webhook_url]
  redirect_to :home
 end

end

app/views/config/config_form.html.erb
<h2>Eventracker Configuration</h2>

<%= form_for @config, url: eventracker_path(@config) do |form| %>
<%= form.text_field :webhook_url %> 
<%= form.submit 'Save' %>
<% end %>

app/views/eventrackers/edit.html.erb
<h2>Eventracker Configuration</h2>

<%= form_for @config, url: eventracker_path(@config) do |form| %>
<%= form.text_field :webhook_url %> 
<%= form.submit 'Save' %>
<% end %>